---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Genome_Release_Flow/Genome_Release_Flow.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/76982/articles/278700/master/file/figures/Genome_Release_Flow/Genome_Release_Flow.png"
